---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/worker: worker
  name: cluster1-worker1
---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/worker: worker
  name: cluster1-worker2